inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - db/schema.rb
    - db/migrate/**/*
    - test/fixtures/**/*
    - tmp/**/*

# -- Performance ---------------------------------------------------------------
Performance/Casecmp:
  Enabled: false

# -- Metrics -------------------------------------------------------------------
Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

# -- Style ---------------------------------------------------------------------
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Style/Lambda:
  EnforcedStyle: literal

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/AsciiComments:
  Enabled: false
